### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [raguay/raguay.github.io#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`index.html`](https://github.com/raguay/raguay.github.io/blob/3821f8cbc858cd11f9b31ada178d1aa507346161/projects/alfredp/alfredanybar/index.html). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by raguay** [comment]
This has been fixed as I've updated to a new CMS system. Thanks for pointing it out.
